### ISSUE TITLE
[Epic] Access node client version tracking

### ISSUE THREAD

**Issue by justinbarry** [onflow/flow#1317]
```[tasklist]
### Tasks
- [ ] https://github.com/onflow/fcl-js/issues/1561
- [ ] https://github.com/onflow/flow-cli/issues/841
- [ ] https://github.com/onflow/flow-go-sdk/issues/341
- [ ] https://github.com/onflow/fcl-js/issues/1562
```
